on: push

name: "Get cpuinfo"
jobs:
  select-runner:
    runs-on: ubuntu-latest
    outputs:
      macos-runner: ${{ steps.macos.outputs.runner }}
    steps:
      - id: macos
        run: |
          echo set-output name=runner::${OVERRIDE_MACOS_RUNNER:-macos-latest}
          echo ::set-output name=runner::${OVERRIDE_MACOS_RUNNER:-macos-latest}
  mac:
    runs-on: macos-latest
    needs: select-runner
    steps:
      - run: echo ${{ needs.select-runner.outputs.macos-runner }}
      - run: |
          sysctl -n machdep.cpu.brand_string
          system_profiler | grep Processor
          sysctl hw
