on: push

name: "Get cpuinfo"
jobs:
  select-runner:
    runs-on: ubuntu-latest
    outputs:
      macos-runner: ${{ steps.macos.outputs.runner }}
    steps:
      - id: macos
        run: |
          echo set-output name=runner::${OVERRIDE_MACOS_RUNNER:-macos-latest}
          echo ::set-output name=runner::${OVERRIDE_MACOS_RUNNER:-macos-latest}
  mac:
    runs-on: ${{ needs.select-runner.outputs.macos-runner }}
    needs: select-runner
    steps:
      - run: |
          sysctl -n machdep.cpu.brand_string
          system_profiler | grep Processor
          sysctl hw
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64
      - run: |
          pip install -r requirements.txt
          python test.py
